//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentReg.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string StudentAddress { get; set; }
        public string StudentEmail { get; set; }
        public Nullable<long> StudentMobileNo { get; set; }
        public Nullable<int> StudentAge { get; set; }
    }
}
